### ISSUE TITLE
Load Button Android Not Working

### ISSUE THREAD

**Issue by Fr0stM0urne** [GracesGames/SimpleFileBrowser#43] opened 2018-07-10 17:22 UTC
### Question, bug or feature

![load](https://user-images.githubusercontent.com/33102679/42526553-90db423a-848f-11e8-95f5-dd18159bd96e.png)
Load button in the demo scene is not working. The one that looks like the download button when selecting files. Do we have add a separate script for it or is it already implemented in the demo.

### Version(s) affected

1.4.0

### Unity version

Unity Version: 2018.1.1f1

**Comment by GracesGames** [comment] 2018-07-10 21:05
I will take a look when I'm back on my desktop. It should work in the demo scene without issues, could you check your (error) log or create a gif/screen capture?

**Comment by Fr0stM0urne** [comment] 2018-07-11 07:46
Thanks for the responses. :)
I used to adb logcat to get this. These lines were appearing when i pressed the load button multiple times. 
![sbfdebug](https://user-images.githubusercontent.com/33102679/42557538-423c2ba2-8508-11e8-9845-83286525159b.png)
There was no response from the andriod application when I pressed the load button.

**Comment by GracesGames** [comment] 2018-07-16 16:24
Hmm I am having troubles reproducing this myself. If anyone has a fix, please let me know.
I'll do some more research, hoping to reproduce.

**Comment by Fr0stM0urne** [comment] 2018-07-17 17:36
What is the output when you press the load button? Are you returned to the main browser scene?

**Comment by GracesGames** [comment] 2018-07-17 17:53
Yes. The file is loaded and the output is shown in the main browser scene.

**Comment by TheRealCatherine** [comment] 2018-07-29 22:53
Ok so I found out in my case its giving a file not found exception after selecting a file and hitting open. The file is there and I'm just selecting it in the SimpleFileBrowser but doing the actual load it fails. I'm guessing something with the path is coming out wrong. Im using a Samsung Galaxy S7 with recent-ish OS (I think 7.0)

 Here is the log:

```
07-29 17:48:05.283: E/Unity(15431): FileNotFoundException: Could not find file "/\\storage\emulated\0\Stages\Testing\Cathy1\Easy\1-1.json"

07-29 17:48:05.283: E/Unity(15431):   at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.Boolean anonymous, System.IO.FileOptions options) [0x0019e] in <f826c2584fc94ec19a48a6576640bdc5>:0 

07-29 17:48:05.283: E/Unity(15431):   at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.IO.FileOptions options) [0x00000] in <f826c2584fc94ec19a48a6576640bdc5>:0 

07-29 17:48:05.283: E/Unity(15431):   at System.IO.FileStream..ctor (System.String path, 
System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.Boolean useAsync) [0x00000] in <f826c2584fc94ec19a48a6576640bdc5>:0 

07-29 17:48:05.283: E/Unity(15431):   at System.Net.FileWebStream..ctor (System.Net.FileWebRequest request, System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare sharing, Sy
```

**Comment by TheRealCatherine** [comment] 2018-07-30 01:14
Ok so at least for us the issue seems to be a Unity bug: https://issuetracker.unity3d.com/issues/system-dot-configuration-dot-configurationerrorsexception-failed-to-load-configuration-section-for-datacontractserializer

**Comment by TheRealCatherine** [comment] 2018-07-30 22:36
We made a version today that uses binary serialzer instead of json and it works fine - so at least in _our_ case I can say loading files from internal phone storage (we have not tested from sd card) using the filebrowser works fine and that our issue was not related to the filebrowser code.

**Comment by GracesGames** [comment] 2018-08-01 16:18
Thanks for the great investigation work! Will close this issue since the problem is external and a workaround is available.

**Closed by GracesGames** 2018-08-01 16:18 UTC
