### ISSUE TITLE
Nullrefrence to  _loadFileText ?

### ISSUE THREAD

**Issue by zealousappex** [GracesGames/SimpleFileBrowser#26] opened 2017-12-12 22:33 UTC
For some reason I am getting a null reference any help would be great!
This is from a new scene.

`NullReferenceException: Object reference not set to an instance of an object
SimpleFileBrowser.Scripts.GracesGames.FileBrowser.OpenFilePanel (UnityEngine.MonoBehaviour callerScript, System.String callbackMethod, System.String fileExtension) (at Assets/SimpleFileBrowser/Scripts/GracesGames/FileBrowser.cs:472)
SimpleFileBrowser.Scripts.GracesGames.MimicFileBrowser.OpenFileBrowserSaveLoad (FileBrowserMode fileBrowserMode) (at Assets/MIMIC/Objects/LevelCreator/MimicFileBrowser.cs:55)
SimpleFileBrowser.Scripts.GracesGames.MimicFileBrowser.OpenFileBrowser (Boolean saving) (at Assets/MIMIC/Objects/LevelCreator/MimicFileBrowser.cs:35)
UnityEngine.Events.InvokableCall`1[System.Boolean].Invoke (Boolean args0) (at C:/buildslave/unity/build/Runtime/Export/UnityEvent.cs:206)
UnityEngine.Events.CachedInvokableCall`1[System.Boolean].Invoke (System.Object[] args) (at C:/buildslave/unity/build/Runtime/Export/UnityEvent.cs:344)
UnityEngine.Events.UnityEvent.Invoke () (at C:/buildslave/unity/build/Runtime/Export/UnityEvent_0.cs:65)
UnityEngine.UI.Button.Press () (at C:/buildslave/unity/build/Extensions/guisystem/UnityEngine.UI/UI/Core/Button.cs:36)
UnityEngine.UI.Button.OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData) (at C:/buildslave/unity/build/Extensions/guisystem/UnityEngine.UI/UI/Core/Button.cs:45)
UnityEngine.EventSystems.ExecuteEvents.Execute (IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at C:/buildslave/unity/build/Extensions/guisystem/UnityEngine.UI/EventSystem/ExecuteEvents.cs:50)
UnityEngine.EventSystems.ExecuteEvents.Execute[IPointerClickHandler] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.EventFunction`1 functor) (at C:/buildslave/unity/build/Extensions/guisystem/UnityEngine.UI/EventSystem/ExecuteEvents.cs:261)
UnityEngine.EventSystems.EventSystem:Update()`

**Comment by GracesGames** [comment] 2017-12-13 01:33
Hmm interesting, never occurred yet.
Which is version is this? Maybe it is a good idea to update to version 1.2.0 (released today).
Let me know if the issue persists.

**Comment by zealousappex** [comment] 2017-12-13 02:45
Hi Grace,
Thank you for the package and work you've done!
I just added a "LoadText" to my GUI and pointed this line of code to it.
`I _loadedText = GameObject.Find("LoadedText");`

Quick question, how can I set the default directory?

**Comment by zealousappex** [comment] 2017-12-13 02:46
ok will update, also I'm using Unity 2017.3.0f2 Beata

**Comment by GracesGames** [comment] 2017-12-13 03:18
Glad to hear you already solved the problem. I'll look into in for the next release.

Setting the default directory is on the Features list, for now you can change the line
`_currentPath = Directory.GetCurrentDirectory();` 
in the _SetupPath_ method of the FileBrowser script. 
For Android, have a look at the _GetAndroidExternalFilesDir_ method.

**Comment by GracesGames** [comment] 2017-12-13 04:59
As the problem is solved, I'll close this issue now :)

**Closed by GracesGames** 2017-12-13 04:59 UTC

**Comment by zealousappex** [comment] 2017-12-13 09:45
thank you!
